export const events = [
  {
    id: '1',
    title: 'Tech Conference',
    date: '2025-05-01',
    location: 'San Francisco, CA',
    description: 'A conference for tech enthusiasts.',
    eventType: 'conference',
    budget: 5000,
    vendors: ['vendor1'], // IDs from vendors.js
  },
  {
    id: '2',
    title: 'Music Festival',
    date: '2025-06-15',
    location: 'Austin, TX',
    description: 'Enjoy live music and food.',
    eventType: 'festival',
    budget: 10000,
    vendors: ['vendor2'],
  },
  {
    id: '3',
    title: 'Art Exhibition',
    date: '2025-07-10',
    location: 'New York, NY',
    description: 'Showcasing local artists.',
    eventType: 'exhibition',
    budget: 3000,
    vendors: [],
  },
  {
    id: '4',
    title: 'Dream Wedding',
    date: '2025-08-20',
    location: 'Los Angeles, CA',
    description: 'A beautiful wedding ceremony.',
    eventType: 'wedding',
    budget: 20000,
    vendors: ['vendor3'],
  },
  {
    id: '5',
    title: 'Birthday Bash',
    date: '2025-09-05',
    location: 'Miami, FL',
    description: 'Celebrating a milestone birthday.',
    eventType: 'birthday',
    budget: 1500,
    vendors: [],
  },
];