export const inspirationEvents = [
  {
    id: 'event1',
    title: 'Vibrant Birthday Bash',
    description: 'A colorful birthday party with balloons and live music.',
    images: ['/assets/birthday/birthday_5.jpg', '/assets/birthday/birthday_6.jpg'],
    eventType: 'birthday',
    location: 'Jalandhar',
    style: 'colorful',
  },
  {
    id: 'event2',
    title: 'Elegant Corporate Conference',
    description: 'A professional conference with top AV tech and catering.',
    images: ['/assets/corporate/corporate_21.jpg', '/assets/corporate/corporate_20.jpg'],
    eventType: 'conference',
    location: 'Ludhiana',
    style: 'modern',
  },
  {
    id: 'event3',
    title: 'Dreamy Sangeet Night',
    description: 'A lively sangeet with dance and decor.',
    images: ['/assets/sangeet/sangeet_1.jpg', '/assets/sangeet/sangeet_6.jpg'],
    eventType: 'sangeet',
    location: 'Patiala',
    style: 'traditional',
  },
  {
    id: 'event4',
    title: 'Romantic Engagement Party',
    description: 'A cozy engagement with floral decor.',
    images: ['/assets/engagement/engagement_14.jpg', '/assets/engagement/engagement_18.jpg'],
    eventType: 'engagement',
    location: 'Amritsar',
    style: 'romantic',
  },
  {
    id: 'event5',
    title: 'Grand Wedding Celebration',
    description: 'A luxurious wedding with top vendors.',
    images: ['/assets/wedding/wedding_13.jpg', '/assets/wedding/wedding_17.jpg'],
    eventType: 'wedding',
    location: 'Bathinda',
    style: 'luxury',
  },
];
